spring.application.name=projet-tutore

spring.datasource.url=jdbc:mysql://localhost:3306/projettutore_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=${JWT_SECRET:cHJvamV0dHV0b3JlX3NlY3JldF9rZXlfZW5zaV8yMDI0X3ZlcnlfbG9uZ19zZWNyZXQ=}
jwt.expiration=86400000
jwt.refresh-expiration=604800000

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

file.upload-dir=uploads/

server.port=8081

spring.jpa.open-in-view=false

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui/index.html
springdoc.swagger-ui.enabled=true